<a href="https://colab.research.google.com/github/CelinaGitau/Python/blob/main/CSV_Mini_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
grades= files.upload()

Saving grades.csv to grades.csv

In [2]:
#read csv file
import pandas as pd
grades = pd.read_csv ("grades.csv")
grades

      Name   Grade
0    Alice      85
1      Bob      92
2  Charlie      78
3    Diana      90
4      Eve      88
5    Frank      76
6    Grace      95
7    Henry      89

In [6]:
# Check column names to check for exact match
print(grades.columns)
grades[" Grade"] = grades[" Grade"].astype(float)
grades

Index(['Name', ' Grade'], dtype='object')

      Name   Grade
0    Alice    85.0
1      Bob    92.0
2  Charlie    78.0
3    Diana    90.0
4      Eve    88.0
5    Frank    76.0
6    Grace    95.0
7    Henry    89.0

In [7]:
print("\nAfter Cleaning (Grades as float):")
print(grades.dtypes)

After Cleaning (Grades as float):
Name       object
 Grade    float64
dtype: object

In [8]:
#summarise the data
avg_grade = grades[" Grade"].mean()
print("Average:", avg_grade)

Average: 86.625

In [11]:
avg_grade = grades[" Grade"].mean()
min_grade = grades[" Grade"].min()
max_grade = grades[" Grade"].max()
num_students = grades[" Grade"].count()

print("Number of Students:", num_students)
print("Average:", avg_grade)
print("Minimum:", min_grade)
print("Maximum:", max_grade)
print ("Number of Students:", num_students)

Number of Students: 8
Average: 86.625
Minimum: 76.0
Maximum: 95.0
Number of Students: 8

In [18]:
#Ouput the summary to a new CSV
summary_df = pd.DataFrame({
    "Average": [avg_grade],
    "Minimum": [min_grade],
    "Maximum": [max_grade],
    "Number of Students": [num_students]
})

#saves the DataFframe as a CSV file
summary_df.to_csv("summary.csv", index=False) # this removes the row numbers

In [19]:
#prints a new line, lets you know the program finished successfully
print("\n Summary CSV file created successfully")

 Summary CSV file created successfully

In [17]:
#Downloading summary csv file
# file is a built-in tool in Colab that lets you upload and download files
from google.colab import files
files.download("summary.csv") # downloads file from Colab to your Pc

In [16]:
summary_df = pd.read_csv("summary.csv")
summary_df

   Average  Minimum  Maximum  Number of Students
0   86.625     76.0     95.0                   8