<a href="https://colab.research.google.com/github/CelinaGitau/Python/blob/main/Sales_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# Import and upload a csv file from your laptop
from google.colab import files
# Please execute this cell to upload your CSV file, ensuring 'sales_data_200.csv' is selected.
files = files.upload()

Saving sales_data_200.csv to sales_data_200.csv

**Inspect the data, read and load the csv file using google colab**

In [17]:
import pandas as pd
sales = pd.read_csv('sales_data_200.csv')
sales

,OrderID,Date,CustomerName,Product,Category,Quantity,UnitPrice,TotalPrice,Region
0,1001,15/08/2025,Emma Johnson,Widget A,Widgets,3.0,20.0,60.0,North
1,1002,17/08/2025,Liam Smith,Gadget B,Gadgets,2.0,35.0,70.0,South
2,1003,19/08/2025,Olivia Brown,Widget A,Widgets,NaN,20.0,NaN,East
3,1004,20/08/2025,Noah Jones,Gadget C,Gadgets,5.0,50.0,250.0,West
4,1005,22/08/2025,Ava Garcia,Widget B,Widgets,4.0,25.0,100.0,North
5,1006,23/08/2025,Isabella Martinez,Gadget A,Gadgets,3.0,NaN,120.0,South
6,1007,25/08/2025,Lucas Davis,Widget C,Widgets,2.0,30.0,60.0,East
7,1008,26/08/2025,Sophia Rodriguez,Gadget B,Gadgets,6.0,35.0,210.0,West
8,1009,28/08/2025,Mason Wilson,Widget A,Widgets,3.0,20.0,60.0,North
9,1010,29/08/2025,Mia Anderson,Gadget C,Gadgets,2.0,50.0,100.0,South
10,1011,30/08/2025,Ethan Thomas,Widget B,Widgets,8.0,25.0,200.0,East
11,1012,01/09/2025,Harper Taylor,Gadget A,Gadgets,1.0,40.0,40.0,West
12,1013,02/09/2025,Logan Moore,Widget C,Widgets,2.0,30.0,60.0,North
13,1014,03/09/2025,Charlotte Jackson,Gadget B,Gadgets,3.0,35.0,105.0,South
14,1015,05/09/2025,Elijah White,Widget A,Widgets,2.0,20.0,40.0,East
15,1016,06/09/2025,Amelia Harris,Gadget C,Gadgets,NaN,50.0,NaN,West
16,1017,08/09/2025,James Martin,Widget A,Widgets,5.0,20.0,100.0,North
17,1018,09/09/2025,Evelyn Thompson,Gadget B,Gadgets,4.0,35.0,140.0,South
18,1019,11/09/2025,Benjamin Garcia,Widget B,Widgets,7.0,25.0,175.0,East
19,1020,12/09/2025,Abigail Martinez,Gadget A,Gadgets,3.0,40.0,120.0,West
20,1021,14/09/2025,Eliana Rodriguez,Widget C,Widgets,2.0,30.0,60.0,North
21,1022,15/09/2025,Alexander Lee,Gadget B,Gadgets,6.0,35.0,210.0,South
22,1023,16/09/2025,Emma Johnson,Widget A,Widgets,3.0,20.0,60.0,North
23,1024,18/09/2025,Liam Smith,Gadget B,Gadgets,NaN,35.0,NaN,South
24,1025,19/09/2025,Olivia Brown,Widget B,Widgets,4.0,25.0,100.0,East
25,1026,21/09/2025,Noah Jones,Gadget C,Gadgets,5.0,50.0,250.0,West
26,1027,22/09/2025,Ava Garcia,Widget C,Widgets,2.0,30.0,60.0,North
27,1028,24/09/2025,Isabella Martinez,Gadget A,Gadgets,3.0,40.0,120.0,South
28,1029,25/09/2025,Lucas Davis,Widget A,Widgets,1.0,20.0,20.0,East
29,1030,27/09/2025,Sophia Rodriguez,Gadget B,Gadgets,6.0,35.0,210.0,West
30,1031,28/09/2025,Mason Wilson,Widget B,Widgets,5.0,25.0,125.0,North
31,1032,30/09/2025,Mia Anderson,Gadget C,Gadgets,3.0,50.0,150.0,South
32,1033,01/10/2025,Ethan Thomas,Widget C,Widgets,4.0,30.0,120.0,East
33,1034,03/10/2025,Harper Taylor,Gadget A,Gadgets,2.0,40.0,80.0,West
34,1035,04/10/2025,Logan Moore,Widget B,Widgets,NaN,25.0,NaN,North
35,1036,06/10/2025,Charlotte Jackson,Gadget B,Gadgets,1.0,35.0,35.0,South
36,1037,08/10/2025,Elijah White,Widget A,Widgets,3.0,20.0,60.0,East
37,1038,09/10/2025,Amelia Harris,Gadget C,Gadgets,5.0,50.0,250.0,West
38,1039,11/10/2025,James Martin,Widget C,Widgets,2.0,30.0,60.0,North
39,1040,12/10/2025,Evelyn Thompson,Gadget A,Gadgets,3.0,40.0,120.0,South

In [ ]:
 # 1. Display the first 10 rows
sales.head (10)

,OrderID,Date,CustomerName,Product,Category,Quantity,UnitPrice,TotalPrice,Region
0,1001,15/08/2025,Emma Johnson,Widget A,Widgets,3.0,20.0,60.0,North
1,1002,17/08/2025,Liam Smith,Gadget B,Gadgets,2.0,35.0,70.0,South
2,1003,19/08/2025,Olivia Brown,Widget A,Widgets,NaN,20.0,NaN,East
3,1004,20/08/2025,Noah Jones,Gadget C,Gadgets,5.0,50.0,250.0,West
4,1005,22/08/2025,Ava Garcia,Widget B,Widgets,4.0,25.0,100.0,North
5,1006,23/08/2025,Isabella Martinez,Gadget A,Gadgets,3.0,NaN,120.0,South
6,1007,25/08/2025,Lucas Davis,Widget C,Widgets,2.0,30.0,60.0,East
7,1008,26/08/2025,Sophia Rodriguez,Gadget B,Gadgets,6.0,35.0,210.0,West
8,1009,28/08/2025,Mason Wilson,Widget A,Widgets,3.0,20.0,60.0,North
9,1010,29/08/2025,Mia Anderson,Gadget C,Gadgets,2.0,50.0,100.0,South

In [ ]:
# 3. Display the `last` rows
sales.tail (10)

,OrderID,Date,CustomerName,Product,Category,Quantity,UnitPrice,TotalPrice,Region
30,1031,28/09/2025,Mason Wilson,Widget B,Widgets,5.0,25.0,125.0,North
31,1032,30/09/2025,Mia Anderson,Gadget C,Gadgets,3.0,50.0,150.0,South
32,1033,01/10/2025,Ethan Thomas,Widget C,Widgets,4.0,30.0,120.0,East
33,1034,03/10/2025,Harper Taylor,Gadget A,Gadgets,2.0,40.0,80.0,West
34,1035,04/10/2025,Logan Moore,Widget B,Widgets,NaN,25.0,NaN,North
35,1036,06/10/2025,Charlotte Jackson,Gadget B,Gadgets,1.0,35.0,35.0,South
36,1037,08/10/2025,Elijah White,Widget A,Widgets,3.0,20.0,60.0,East
37,1038,09/10/2025,Amelia Harris,Gadget C,Gadgets,5.0,50.0,250.0,West
38,1039,11/10/2025,James Martin,Widget C,Widgets,2.0,30.0,60.0,North
39,1040,12/10/2025,Evelyn Thompson,Gadget A,Gadgets,3.0,40.0,120.0,South

In [ ]:
# 4. Showing the total numbers of rows and columns
rows, columns = sales.shape
print(f"The DataFrame has {rows} rows and {columns} columns.")

The DataFrame has 40 rows and 9 columns.

## **Task 2: Selecting Specific Data**


##### Create DataFrame
`sales = pd.read_csv('sales_data_200.csv')`

##### Cleans the column names by removing extra spaces at the start or end
`sales.columns = sales.columns.str.strip()`

##### Selects only the columns you want from th dataset
`selected_columns = sales[['OrderID', 'CustomerName', 'Product', 'TotalPrice']]`

In [ ]:
# select only the columns (OrderID, CustomerName, Product and TotalPrice)
import pandas as pd
sales = pd.read_csv('sales_data_200.csv')
sales.columns = sales.columns.str.strip()
selected_columns = sales[['OrderID', 'CustomerName', 'Product', 'TotalPrice']]
print(selected_columns)

    OrderID       CustomerName   Product  TotalPrice
0      1001       Emma Johnson  Widget A        60.0
1      1002         Liam Smith  Gadget B        70.0
2      1003       Olivia Brown  Widget A         NaN
3      1004         Noah Jones  Gadget C       250.0
4      1005         Ava Garcia  Widget B       100.0
5      1006  Isabella Martinez  Gadget A       120.0
6      1007        Lucas Davis  Widget C        60.0
7      1008   Sophia Rodriguez  Gadget B       210.0
8      1009       Mason Wilson  Widget A        60.0
9      1010       Mia Anderson  Gadget C       100.0
10     1011       Ethan Thomas  Widget B       200.0
11     1012      Harper Taylor  Gadget A        40.0
12     1013        Logan Moore  Widget C        60.0
13     1014  Charlotte Jackson  Gadget B       105.0
14     1015       Elijah White  Widget A        40.0
15     1016      Amelia Harris  Gadget C         NaN
16     1017       James Martin  Widget A       100.0
17     1018    Evelyn Thompson  Gadget B       140.0
18     1019    Benjamin Garcia  Widget B       175.0
19     1020   Abigail Martinez  Gadget A       120.0
20     1021   Eliana Rodriguez  Widget C        60.0
21     1022      Alexander Lee  Gadget B       210.0
22     1023       Emma Johnson  Widget A        60.0
23     1024         Liam Smith  Gadget B         NaN
24     1025       Olivia Brown  Widget B       100.0
25     1026         Noah Jones  Gadget C       250.0
26     1027         Ava Garcia  Widget C        60.0
27     1028  Isabella Martinez  Gadget A       120.0
28     1029        Lucas Davis  Widget A        20.0
29     1030   Sophia Rodriguez  Gadget B       210.0
30     1031       Mason Wilson  Widget B       125.0
31     1032       Mia Anderson  Gadget C       150.0
32     1033       Ethan Thomas  Widget C       120.0
33     1034      Harper Taylor  Gadget A        80.0
34     1035        Logan Moore  Widget B         NaN
35     1036  Charlotte Jackson  Gadget B        35.0
36     1037       Elijah White  Widget A        60.0
37     1038      Amelia Harris  Gadget C       250.0
38     1039       James Martin  Widget C        60.0
39     1040    Evelyn Thompson  Gadget A       120.0

In [ ]:
# 2. Select all orders where Region is "North"
north_region_orders = sales[sales['Region'] == 'North']
print(north_region_orders)

    OrderID        Date      CustomerName   Product Category  Quantity  \
0      1001  15/08/2025      Emma Johnson  Widget A  Widgets       3.0
4      1005  22/08/2025        Ava Garcia  Widget B  Widgets       4.0
8      1009  28/08/2025      Mason Wilson  Widget A  Widgets       3.0
12     1013  02/09/2025       Logan Moore  Widget C  Widgets       2.0
16     1017  08/09/2025      James Martin  Widget A  Widgets       5.0
20     1021  14/09/2025  Eliana Rodriguez  Widget C  Widgets       2.0
22     1023  16/09/2025      Emma Johnson  Widget A  Widgets       3.0
26     1027  22/09/2025        Ava Garcia  Widget C  Widgets       2.0
30     1031  28/09/2025      Mason Wilson  Widget B  Widgets       5.0
34     1035  04/10/2025       Logan Moore  Widget B  Widgets       NaN
38     1039  11/10/2025      James Martin  Widget C  Widgets       2.0

    UnitPrice  TotalPrice Region
0        20.0        60.0  North
4        25.0       100.0  North
8        20.0        60.0  North
12       30.0        60.0  North
16       20.0       100.0  North
20       30.0        60.0  North
22       20.0        60.0  North
26       30.0        60.0  North
30       25.0       125.0  North
34       25.0         NaN  North
38       30.0        60.0  North

In [ ]:
# 3.Sales orders with Quantity (greater than or equal to) >=5
Quantity_orders = sales[sales['Quantity'] >= 5]
print(Quantity_orders)

    OrderID        Date      CustomerName   Product Category  Quantity  \
3      1004  20/08/2025        Noah Jones  Gadget C  Gadgets       5.0
7      1008  26/08/2025  Sophia Rodriguez  Gadget B  Gadgets       6.0
10     1011  30/08/2025      Ethan Thomas  Widget B  Widgets       8.0
16     1017  08/09/2025      James Martin  Widget A  Widgets       5.0
18     1019  11/09/2025   Benjamin Garcia  Widget B  Widgets       7.0
21     1022  15/09/2025     Alexander Lee  Gadget B  Gadgets       6.0
25     1026  21/09/2025        Noah Jones  Gadget C  Gadgets       5.0
29     1030  27/09/2025  Sophia Rodriguez  Gadget B  Gadgets       6.0
30     1031  28/09/2025      Mason Wilson  Widget B  Widgets       5.0
37     1038  09/10/2025     Amelia Harris  Gadget C  Gadgets       5.0

    UnitPrice  TotalPrice Region
3        50.0       250.0   West
7        35.0       210.0   West
10       25.0       200.0   East
16       20.0       100.0  North
18       25.0       175.0   East
21       35.0       210.0  South
25       50.0       250.0   West
29       35.0       210.0   West
30       25.0       125.0  North
37       50.0       250.0   West

**Filtering data using `isin()`**
- This selects only certain rows from the dataset based on the product name

In [ ]:
# 4. Select orders for "`Widget A`" or "`Gadget B1`"

from numpy import isin
quantity_orders = sales[sales['Product'].isin (['Widget A', 'Gadget B'])]
print(quantity_orders)

    OrderID        Date       CustomerName   Product Category  Quantity  \
0      1001  15/08/2025       Emma Johnson  Widget A  Widgets       3.0
1      1002  17/08/2025         Liam Smith  Gadget B  Gadgets       2.0
2      1003  19/08/2025       Olivia Brown  Widget A  Widgets       NaN
7      1008  26/08/2025   Sophia Rodriguez  Gadget B  Gadgets       6.0
8      1009  28/08/2025       Mason Wilson  Widget A  Widgets       3.0
13     1014  03/09/2025  Charlotte Jackson  Gadget B  Gadgets       3.0
14     1015  05/09/2025       Elijah White  Widget A  Widgets       2.0
16     1017  08/09/2025       James Martin  Widget A  Widgets       5.0
17     1018  09/09/2025    Evelyn Thompson  Gadget B  Gadgets       4.0
21     1022  15/09/2025      Alexander Lee  Gadget B  Gadgets       6.0
22     1023  16/09/2025       Emma Johnson  Widget A  Widgets       3.0
23     1024  18/09/2025         Liam Smith  Gadget B  Gadgets       NaN
28     1029  25/09/2025        Lucas Davis  Widget A  Widgets       1.0
29     1030  27/09/2025   Sophia Rodriguez  Gadget B  Gadgets       6.0
35     1036  06/10/2025  Charlotte Jackson  Gadget B  Gadgets       1.0
36     1037  08/10/2025       Elijah White  Widget A  Widgets       3.0

    UnitPrice  TotalPrice Region
0        20.0        60.0  North
1        35.0        70.0  South
2        20.0         NaN   East
7        35.0       210.0   West
8        20.0        60.0  North
13       35.0       105.0  South
14       20.0        40.0   East
16       20.0       100.0  North
17       35.0       140.0  South
21       35.0       210.0  South
22       20.0        60.0  North
23       35.0         NaN  South
28       20.0        20.0   East
29       35.0       210.0   West
35       35.0        35.0  South
36       20.0        60.0   East

## Task 3: Handling Null Values

Checks which columns have missing/null values

In [ ]:
sales.isnull ()

,OrderID,Date,CustomerName,Product,Category,Quantity,UnitPrice,TotalPrice,Region
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,True,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,True,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,True,False,True,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,True,False,True,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,True,False,True,False
35,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False

2. **Count the number of null values per columns**

In [ ]:
# Checks every cell and returns `true` if its missing, `false` if not
sales.isnull (). values

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

3. **Delete rows that have nulls or missing values**

  `sales.dropna (inplace= True)`

  Removes any rows that have missing (nulls) values

  `inplace=True` means it changes the original data directly

In [ ]:
# Removes all the nulls
import pandas as pd
sales = pd.read_csv('sales_data_200.csv')
sales.dropna (inplace= True)
print (sales.to_string)

<bound method DataFrame.to_string of     OrderID        Date       CustomerName   Product Category  Quantity  \
0      1001  15/08/2025       Emma Johnson  Widget A  Widgets       3.0
1      1002  17/08/2025         Liam Smith  Gadget B  Gadgets       2.0
3      1004  20/08/2025         Noah Jones  Gadget C  Gadgets       5.0
4      1005  22/08/2025         Ava Garcia  Widget B  Widgets       4.0
6      1007  25/08/2025        Lucas Davis  Widget C  Widgets       2.0
7      1008  26/08/2025   Sophia Rodriguez  Gadget B  Gadgets       6.0
8      1009  28/08/2025       Mason Wilson  Widget A  Widgets       3.0
9      1010  29/08/2025       Mia Anderson  Gadget C  Gadgets       2.0
10     1011  30/08/2025       Ethan Thomas  Widget B  Widgets       8.0
11     1012  01/09/2025      Harper Taylor  Gadget A  Gadgets       1.0
12     1013  02/09/2025        Logan Moore  Widget C  Widgets       2.0
13     1014  03/09/2025  Charlotte Jackson  Gadget B  Gadgets       3.0
14     1015  05/09/2025       Elijah White  Widget A  Widgets       2.0
16     1017  08/09/2025       James Martin  Widget A  Widgets       5.0
17     1018  09/09/2025    Evelyn Thompson  Gadget B  Gadgets       4.0
18     1019  11/09/2025    Benjamin Garcia  Widget B  Widgets       7.0
19     1020  12/09/2025   Abigail Martinez  Gadget A  Gadgets       3.0
20     1021  14/09/2025   Eliana Rodriguez  Widget C  Widgets       2.0
21     1022  15/09/2025      Alexander Lee  Gadget B  Gadgets       6.0
22     1023  16/09/2025       Emma Johnson  Widget A  Widgets       3.0
24     1025  19/09/2025       Olivia Brown  Widget B  Widgets       4.0
25     1026  21/09/2025         Noah Jones  Gadget C  Gadgets       5.0
26     1027  22/09/2025         Ava Garcia  Widget C  Widgets       2.0
27     1028  24/09/2025  Isabella Martinez  Gadget A  Gadgets       3.0
28     1029  25/09/2025        Lucas Davis  Widget A  Widgets       1.0
29     1030  27/09/2025   Sophia Rodriguez  Gadget B  Gadgets       6.0
30     1031  28/09/2025       Mason Wilson  Widget B  Widgets       5.0
31     1032  30/09/2025       Mia Anderson  Gadget C  Gadgets       3.0
32     1033  01/10/2025       Ethan Thomas  Widget C  Widgets       4.0
33     1034  03/10/2025      Harper Taylor  Gadget A  Gadgets       2.0
35     1036  06/10/2025  Charlotte Jackson  Gadget B  Gadgets       1.0
36     1037  08/10/2025       Elijah White  Widget A  Widgets       3.0
37     1038  09/10/2025      Amelia Harris  Gadget C  Gadgets       5.0
38     1039  11/10/2025       James Martin  Widget C  Widgets       2.0
39     1040  12/10/2025    Evelyn Thompson  Gadget A  Gadgets       3.0

    UnitPrice  TotalPrice Region
0        20.0        60.0  North
1        35.0        70.0  South
3        50.0       250.0   West
4        25.0       100.0  North
6        30.0        60.0   East
7        35.0       210.0   West
8        20.0        60.0  North
9        50.0       100.0  South
10       25.0       200.0   East
11       40.0        40.0   West
12       30.0        60.0  North
13       35.0       105.0  South
14       20.0        40.0   East
16       20.0       100.0  North
17       35.0       140.0  South
18       25.0       175.0   East
19       40.0       120.0   West
20       30.0        60.0  North
21       35.0       210.0  South
22       20.0        60.0  North
24       25.0       100.0   East
25       50.0       250.0   West
26       30.0        60.0  North
27       40.0       120.0  South
28       20.0        20.0   East
29       35.0       210.0   West
30       25.0       125.0  North
31       50.0       150.0  South
32       30.0       120.0   East
33       40.0        80.0   West
35       35.0        35.0  South
36       20.0        60.0   East
37       50.0       250.0   West
38       30.0        60.0  North
39       40.0       120.0  South  >

## **Task 4: Handling Duplicates**

Checks if there are duplicate rows in the dataset

In [41]:
sales.duplicated ().values

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [42]:
# Delete duplicate rows
sales.duplicated ()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
dtype: bool

In [40]:
# Removes repeated (duplicate), rows from your data
# keeps only one copy of each row
# Displays cleaned data

sales.drop_duplicates (inplace=True)
print (sales.to_string)

<bound method DataFrame.to_string of     OrderID        Date       CustomerName   Product Category  Quantity  \
0      1001  15/08/2025       Emma Johnson  Widget A  Widgets       3.0
1      1002  17/08/2025         Liam Smith  Gadget B  Gadgets       2.0
2      1003  19/08/2025       Olivia Brown  Widget A  Widgets       NaN
3      1004  20/08/2025         Noah Jones  Gadget C  Gadgets       5.0
4      1005  22/08/2025         Ava Garcia  Widget B  Widgets       4.0
5      1006  23/08/2025  Isabella Martinez  Gadget A  Gadgets       3.0
6      1007  25/08/2025        Lucas Davis  Widget C  Widgets       2.0
7      1008  26/08/2025   Sophia Rodriguez  Gadget B  Gadgets       6.0
8      1009  28/08/2025       Mason Wilson  Widget A  Widgets       3.0
9      1010  29/08/2025       Mia Anderson  Gadget C  Gadgets       2.0
10     1011  30/08/2025       Ethan Thomas  Widget B  Widgets       8.0
11     1012  01/09/2025      Harper Taylor  Gadget A  Gadgets       1.0
12     1013  02/09/2025        Logan Moore  Widget C  Widgets       2.0
13     1014  03/09/2025  Charlotte Jackson  Gadget B  Gadgets       3.0
14     1015  05/09/2025       Elijah White  Widget A  Widgets       2.0
15     1016  06/09/2025      Amelia Harris  Gadget C  Gadgets       NaN
16     1017  08/09/2025       James Martin  Widget A  Widgets       5.0
17     1018  09/09/2025    Evelyn Thompson  Gadget B  Gadgets       4.0
18     1019  11/09/2025    Benjamin Garcia  Widget B  Widgets       7.0
19     1020  12/09/2025   Abigail Martinez  Gadget A  Gadgets       3.0
20     1021  14/09/2025   Eliana Rodriguez  Widget C  Widgets       2.0
21     1022  15/09/2025      Alexander Lee  Gadget B  Gadgets       6.0
22     1023  16/09/2025       Emma Johnson  Widget A  Widgets       3.0
23     1024  18/09/2025         Liam Smith  Gadget B  Gadgets       NaN
24     1025  19/09/2025       Olivia Brown  Widget B  Widgets       4.0
25     1026  21/09/2025         Noah Jones  Gadget C  Gadgets       5.0
26     1027  22/09/2025         Ava Garcia  Widget C  Widgets       2.0
27     1028  24/09/2025  Isabella Martinez  Gadget A  Gadgets       3.0
28     1029  25/09/2025        Lucas Davis  Widget A  Widgets       1.0
29     1030  27/09/2025   Sophia Rodriguez  Gadget B  Gadgets       6.0
30     1031  28/09/2025       Mason Wilson  Widget B  Widgets       5.0
31     1032  30/09/2025       Mia Anderson  Gadget C  Gadgets       3.0
32     1033  01/10/2025       Ethan Thomas  Widget C  Widgets       4.0
33     1034  03/10/2025      Harper Taylor  Gadget A  Gadgets       2.0
34     1035  04/10/2025        Logan Moore  Widget B  Widgets       NaN
35     1036  06/10/2025  Charlotte Jackson  Gadget B  Gadgets       1.0
36     1037  08/10/2025       Elijah White  Widget A  Widgets       3.0
37     1038  09/10/2025      Amelia Harris  Gadget C  Gadgets       5.0
38     1039  11/10/2025       James Martin  Widget C  Widgets       2.0
39     1040  12/10/2025    Evelyn Thompson  Gadget A  Gadgets       3.0

    UnitPrice  TotalPrice Region
0        20.0        60.0  North
1        35.0        70.0  South
2        20.0         NaN   East
3        50.0       250.0   West
4        25.0       100.0  North
5         NaN       120.0  South
6        30.0        60.0   East
7        35.0       210.0   West
8        20.0        60.0  North
9        50.0       100.0  South
10       25.0       200.0   East
11       40.0        40.0   West
12       30.0        60.0  North
13       35.0       105.0  South
14       20.0        40.0   East
15       50.0         NaN   West
16       20.0       100.0  North
17       35.0       140.0  South
18       25.0       175.0   East
19       40.0       120.0   West
20       30.0        60.0  North
21       35.0       210.0  South
22       20.0        60.0  North
23       35.0         NaN  South
24       25.0       100.0   East
25       50.0       250.0   West
26       30.0        60.0  North
27       40.0       120.0  South
28       20.0        20.0   East
29       35.0       210.0   West
30       25.0       125.0  North
31       50.0       150.0  South
32       30.0       120.0   East
33       40.0        80.0   West
34       25.0         NaN  North
35       35.0        35.0  South
36       20.0        60.0   East
37       50.0       250.0   West
38       30.0        60.0  North
39       40.0       120.0  South  >

## **Task 5: Modifying Columns**

Rename the column CustomerName to Customer

In [44]:
sales.rename (columns = {'CustomerName': 'Customer'}, inplace = True)
print('Customer')
sales

Customer

,OrderID,Date,Customer,Product,Category,Quantity,UnitPrice,TotalPrice,Region
0,1001,15/08/2025,Emma Johnson,Widget A,Widgets,3.0,20.0,60.0,North
1,1002,17/08/2025,Liam Smith,Gadget B,Gadgets,2.0,35.0,70.0,South
2,1003,19/08/2025,Olivia Brown,Widget A,Widgets,NaN,20.0,NaN,East
3,1004,20/08/2025,Noah Jones,Gadget C,Gadgets,5.0,50.0,250.0,West
4,1005,22/08/2025,Ava Garcia,Widget B,Widgets,4.0,25.0,100.0,North
5,1006,23/08/2025,Isabella Martinez,Gadget A,Gadgets,3.0,NaN,120.0,South
6,1007,25/08/2025,Lucas Davis,Widget C,Widgets,2.0,30.0,60.0,East
7,1008,26/08/2025,Sophia Rodriguez,Gadget B,Gadgets,6.0,35.0,210.0,West
8,1009,28/08/2025,Mason Wilson,Widget A,Widgets,3.0,20.0,60.0,North
9,1010,29/08/2025,Mia Anderson,Gadget C,Gadgets,2.0,50.0,100.0,South
10,1011,30/08/2025,Ethan Thomas,Widget B,Widgets,8.0,25.0,200.0,East
11,1012,01/09/2025,Harper Taylor,Gadget A,Gadgets,1.0,40.0,40.0,West
12,1013,02/09/2025,Logan Moore,Widget C,Widgets,2.0,30.0,60.0,North
13,1014,03/09/2025,Charlotte Jackson,Gadget B,Gadgets,3.0,35.0,105.0,South
14,1015,05/09/2025,Elijah White,Widget A,Widgets,2.0,20.0,40.0,East
15,1016,06/09/2025,Amelia Harris,Gadget C,Gadgets,NaN,50.0,NaN,West
16,1017,08/09/2025,James Martin,Widget A,Widgets,5.0,20.0,100.0,North
17,1018,09/09/2025,Evelyn Thompson,Gadget B,Gadgets,4.0,35.0,140.0,South
18,1019,11/09/2025,Benjamin Garcia,Widget B,Widgets,7.0,25.0,175.0,East
19,1020,12/09/2025,Abigail Martinez,Gadget A,Gadgets,3.0,40.0,120.0,West
20,1021,14/09/2025,Eliana Rodriguez,Widget C,Widgets,2.0,30.0,60.0,North
21,1022,15/09/2025,Alexander Lee,Gadget B,Gadgets,6.0,35.0,210.0,South
22,1023,16/09/2025,Emma Johnson,Widget A,Widgets,3.0,20.0,60.0,North
23,1024,18/09/2025,Liam Smith,Gadget B,Gadgets,NaN,35.0,NaN,South
24,1025,19/09/2025,Olivia Brown,Widget B,Widgets,4.0,25.0,100.0,East
25,1026,21/09/2025,Noah Jones,Gadget C,Gadgets,5.0,50.0,250.0,West
26,1027,22/09/2025,Ava Garcia,Widget C,Widgets,2.0,30.0,60.0,North
27,1028,24/09/2025,Isabella Martinez,Gadget A,Gadgets,3.0,40.0,120.0,South
28,1029,25/09/2025,Lucas Davis,Widget A,Widgets,1.0,20.0,20.0,East
29,1030,27/09/2025,Sophia Rodriguez,Gadget B,Gadgets,6.0,35.0,210.0,West
30,1031,28/09/2025,Mason Wilson,Widget B,Widgets,5.0,25.0,125.0,North
31,1032,30/09/2025,Mia Anderson,Gadget C,Gadgets,3.0,50.0,150.0,South
32,1033,01/10/2025,Ethan Thomas,Widget C,Widgets,4.0,30.0,120.0,East
33,1034,03/10/2025,Harper Taylor,Gadget A,Gadgets,2.0,40.0,80.0,West
34,1035,04/10/2025,Logan Moore,Widget B,Widgets,NaN,25.0,NaN,North
35,1036,06/10/2025,Charlotte Jackson,Gadget B,Gadgets,1.0,35.0,35.0,South
36,1037,08/10/2025,Elijah White,Widget A,Widgets,3.0,20.0,60.0,East
37,1038,09/10/2025,Amelia Harris,Gadget C,Gadgets,5.0,50.0,250.0,West
38,1039,11/10/2025,James Martin,Widget C,Widgets,2.0,30.0,60.0,North
39,1040,12/10/2025,Evelyn Thompson,Gadget A,Gadgets,3.0,40.0,120.0,South

2. **Rename UnitPrice to PricePerUnit**

In [45]:
sales.rename (columns = {'UnitPrice': 'PricePerUnit'}, inplace = True)
print('PricePerUnit')
sales

PricePerUnit

,OrderID,Date,Customer,Product,Category,Quantity,PricePerUnit,TotalPrice,Region
0,1001,15/08/2025,Emma Johnson,Widget A,Widgets,3.0,20.0,60.0,North
1,1002,17/08/2025,Liam Smith,Gadget B,Gadgets,2.0,35.0,70.0,South
2,1003,19/08/2025,Olivia Brown,Widget A,Widgets,NaN,20.0,NaN,East
3,1004,20/08/2025,Noah Jones,Gadget C,Gadgets,5.0,50.0,250.0,West
4,1005,22/08/2025,Ava Garcia,Widget B,Widgets,4.0,25.0,100.0,North
5,1006,23/08/2025,Isabella Martinez,Gadget A,Gadgets,3.0,NaN,120.0,South
6,1007,25/08/2025,Lucas Davis,Widget C,Widgets,2.0,30.0,60.0,East
7,1008,26/08/2025,Sophia Rodriguez,Gadget B,Gadgets,6.0,35.0,210.0,West
8,1009,28/08/2025,Mason Wilson,Widget A,Widgets,3.0,20.0,60.0,North
9,1010,29/08/2025,Mia Anderson,Gadget C,Gadgets,2.0,50.0,100.0,South
10,1011,30/08/2025,Ethan Thomas,Widget B,Widgets,8.0,25.0,200.0,East
11,1012,01/09/2025,Harper Taylor,Gadget A,Gadgets,1.0,40.0,40.0,West
12,1013,02/09/2025,Logan Moore,Widget C,Widgets,2.0,30.0,60.0,North
13,1014,03/09/2025,Charlotte Jackson,Gadget B,Gadgets,3.0,35.0,105.0,South
14,1015,05/09/2025,Elijah White,Widget A,Widgets,2.0,20.0,40.0,East
15,1016,06/09/2025,Amelia Harris,Gadget C,Gadgets,NaN,50.0,NaN,West
16,1017,08/09/2025,James Martin,Widget A,Widgets,5.0,20.0,100.0,North
17,1018,09/09/2025,Evelyn Thompson,Gadget B,Gadgets,4.0,35.0,140.0,South
18,1019,11/09/2025,Benjamin Garcia,Widget B,Widgets,7.0,25.0,175.0,East
19,1020,12/09/2025,Abigail Martinez,Gadget A,Gadgets,3.0,40.0,120.0,West
20,1021,14/09/2025,Eliana Rodriguez,Widget C,Widgets,2.0,30.0,60.0,North
21,1022,15/09/2025,Alexander Lee,Gadget B,Gadgets,6.0,35.0,210.0,South
22,1023,16/09/2025,Emma Johnson,Widget A,Widgets,3.0,20.0,60.0,North
23,1024,18/09/2025,Liam Smith,Gadget B,Gadgets,NaN,35.0,NaN,South
24,1025,19/09/2025,Olivia Brown,Widget B,Widgets,4.0,25.0,100.0,East
25,1026,21/09/2025,Noah Jones,Gadget C,Gadgets,5.0,50.0,250.0,West
26,1027,22/09/2025,Ava Garcia,Widget C,Widgets,2.0,30.0,60.0,North
27,1028,24/09/2025,Isabella Martinez,Gadget A,Gadgets,3.0,40.0,120.0,South
28,1029,25/09/2025,Lucas Davis,Widget A,Widgets,1.0,20.0,20.0,East
29,1030,27/09/2025,Sophia Rodriguez,Gadget B,Gadgets,6.0,35.0,210.0,West
30,1031,28/09/2025,Mason Wilson,Widget B,Widgets,5.0,25.0,125.0,North
31,1032,30/09/2025,Mia Anderson,Gadget C,Gadgets,3.0,50.0,150.0,South
32,1033,01/10/2025,Ethan Thomas,Widget C,Widgets,4.0,30.0,120.0,East
33,1034,03/10/2025,Harper Taylor,Gadget A,Gadgets,2.0,40.0,80.0,West
34,1035,04/10/2025,Logan Moore,Widget B,Widgets,NaN,25.0,NaN,North
35,1036,06/10/2025,Charlotte Jackson,Gadget B,Gadgets,1.0,35.0,35.0,South
36,1037,08/10/2025,Elijah White,Widget A,Widgets,3.0,20.0,60.0,East
37,1038,09/10/2025,Amelia Harris,Gadget C,Gadgets,5.0,50.0,250.0,West
38,1039,11/10/2025,James Martin,Widget C,Widgets,2.0,30.0,60.0,North
39,1040,12/10/2025,Evelyn Thompson,Gadget A,Gadgets,3.0,40.0,120.0,South

## **Task 6: Changing Data Types**

In [47]:
#Convert Date to a date/timetype
sales['Date'] = pd.to_datetime (sales['Date'], format= '%d/%m/%Y')
print (sales ['Date']. dtype)
print (sales.to_string)

datetime64[ns]
<bound method DataFrame.to_string of     OrderID       Date           Customer   Product Category  Quantity  \
0      1001 2025-08-15       Emma Johnson  Widget A  Widgets       3.0
1      1002 2025-08-17         Liam Smith  Gadget B  Gadgets       2.0
2      1003 2025-08-19       Olivia Brown  Widget A  Widgets       NaN
3      1004 2025-08-20         Noah Jones  Gadget C  Gadgets       5.0
4      1005 2025-08-22         Ava Garcia  Widget B  Widgets       4.0
5      1006 2025-08-23  Isabella Martinez  Gadget A  Gadgets       3.0
6      1007 2025-08-25        Lucas Davis  Widget C  Widgets       2.0
7      1008 2025-08-26   Sophia Rodriguez  Gadget B  Gadgets       6.0
8      1009 2025-08-28       Mason Wilson  Widget A  Widgets       3.0
9      1010 2025-08-29       Mia Anderson  Gadget C  Gadgets       2.0
10     1011 2025-08-30       Ethan Thomas  Widget B  Widgets       8.0
11     1012 2025-09-01      Harper Taylor  Gadget A  Gadgets       1.0
12     1013 2025-09-02        Logan Moore  Widget C  Widgets       2.0
13     1014 2025-09-03  Charlotte Jackson  Gadget B  Gadgets       3.0
14     1015 2025-09-05       Elijah White  Widget A  Widgets       2.0
15     1016 2025-09-06      Amelia Harris  Gadget C  Gadgets       NaN
16     1017 2025-09-08       James Martin  Widget A  Widgets       5.0
17     1018 2025-09-09    Evelyn Thompson  Gadget B  Gadgets       4.0
18     1019 2025-09-11    Benjamin Garcia  Widget B  Widgets       7.0
19     1020 2025-09-12   Abigail Martinez  Gadget A  Gadgets       3.0
20     1021 2025-09-14   Eliana Rodriguez  Widget C  Widgets       2.0
21     1022 2025-09-15      Alexander Lee  Gadget B  Gadgets       6.0
22     1023 2025-09-16       Emma Johnson  Widget A  Widgets       3.0
23     1024 2025-09-18         Liam Smith  Gadget B  Gadgets       NaN
24     1025 2025-09-19       Olivia Brown  Widget B  Widgets       4.0
25     1026 2025-09-21         Noah Jones  Gadget C  Gadgets       5.0
26     1027 2025-09-22         Ava Garcia  Widget C  Widgets       2.0
27     1028 2025-09-24  Isabella Martinez  Gadget A  Gadgets       3.0
28     1029 2025-09-25        Lucas Davis  Widget A  Widgets       1.0
29     1030 2025-09-27   Sophia Rodriguez  Gadget B  Gadgets       6.0
30     1031 2025-09-28       Mason Wilson  Widget B  Widgets       5.0
31     1032 2025-09-30       Mia Anderson  Gadget C  Gadgets       3.0
32     1033 2025-10-01       Ethan Thomas  Widget C  Widgets       4.0
33     1034 2025-10-03      Harper Taylor  Gadget A  Gadgets       2.0
34     1035 2025-10-04        Logan Moore  Widget B  Widgets       NaN
35     1036 2025-10-06  Charlotte Jackson  Gadget B  Gadgets       1.0
36     1037 2025-10-08       Elijah White  Widget A  Widgets       3.0
37     1038 2025-10-09      Amelia Harris  Gadget C  Gadgets       5.0
38     1039 2025-10-11       James Martin  Widget C  Widgets       2.0
39     1040 2025-10-12    Evelyn Thompson  Gadget A  Gadgets       3.0

    PricePerUnit  TotalPrice Region
0           20.0        60.0  North
1           35.0        70.0  South
2           20.0         NaN   East
3           50.0       250.0   West
4           25.0       100.0  North
5            NaN       120.0  South
6           30.0        60.0   East
7           35.0       210.0   West
8           20.0        60.0  North
9           50.0       100.0  South
10          25.0       200.0   East
11          40.0        40.0   West
12          30.0        60.0  North
13          35.0       105.0  South
14          20.0        40.0   East
15          50.0         NaN   West
16          20.0       100.0  North
17          35.0       140.0  South
18          25.0       175.0   East
19          40.0       120.0   West
20          30.0        60.0  North
21          35.0       210.0  South
22          20.0        60.0  North
23          35.0         NaN  South
24          25.0       100.0   East
25          50.0       250.0   West
26          30.0        60.0  North
27          40.0       120.0  South
28          20.0        20.0   East
29          35.0       210.0   West
30          25.0       125.0  North
31          50.0       150.0  South
32          30.0       120.0   East
33          40.0        80.0   West
34          25.0         NaN  North
35          35.0        35.0  South
36          20.0        60.0   East
37          50.0       250.0   West
38          30.0        60.0  North
39          40.0       120.0  South  >

#### **Convert Quantity to an integer**

`fillna(0)` - replaces any missing value in the Quantity column with `0`

`astype(int)` - converts the column values to integer numbers

Checks the type of the column and print the cleaned table

In [49]:
# Convert Quantity to an integer( after handling nulls)
sales.dropna (inplace= True)
sales['Quantity'] = sales['Quantity'].fillna (0).astype(int)
print (sales ['Quantity']. dtype)
print (sales.to_string)

int64
<bound method DataFrame.to_string of     OrderID       Date           Customer   Product Category  Quantity  \
0      1001 2025-08-15       Emma Johnson  Widget A  Widgets         3
1      1002 2025-08-17         Liam Smith  Gadget B  Gadgets         2
3      1004 2025-08-20         Noah Jones  Gadget C  Gadgets         5
4      1005 2025-08-22         Ava Garcia  Widget B  Widgets         4
6      1007 2025-08-25        Lucas Davis  Widget C  Widgets         2
7      1008 2025-08-26   Sophia Rodriguez  Gadget B  Gadgets         6
8      1009 2025-08-28       Mason Wilson  Widget A  Widgets         3
9      1010 2025-08-29       Mia Anderson  Gadget C  Gadgets         2
10     1011 2025-08-30       Ethan Thomas  Widget B  Widgets         8
11     1012 2025-09-01      Harper Taylor  Gadget A  Gadgets         1
12     1013 2025-09-02        Logan Moore  Widget C  Widgets         2
13     1014 2025-09-03  Charlotte Jackson  Gadget B  Gadgets         3
14     1015 2025-09-05       Elijah White  Widget A  Widgets         2
16     1017 2025-09-08       James Martin  Widget A  Widgets         5
17     1018 2025-09-09    Evelyn Thompson  Gadget B  Gadgets         4
18     1019 2025-09-11    Benjamin Garcia  Widget B  Widgets         7
19     1020 2025-09-12   Abigail Martinez  Gadget A  Gadgets         3
20     1021 2025-09-14   Eliana Rodriguez  Widget C  Widgets         2
21     1022 2025-09-15      Alexander Lee  Gadget B  Gadgets         6
22     1023 2025-09-16       Emma Johnson  Widget A  Widgets         3
24     1025 2025-09-19       Olivia Brown  Widget B  Widgets         4
25     1026 2025-09-21         Noah Jones  Gadget C  Gadgets         5
26     1027 2025-09-22         Ava Garcia  Widget C  Widgets         2
27     1028 2025-09-24  Isabella Martinez  Gadget A  Gadgets         3
28     1029 2025-09-25        Lucas Davis  Widget A  Widgets         1
29     1030 2025-09-27   Sophia Rodriguez  Gadget B  Gadgets         6
30     1031 2025-09-28       Mason Wilson  Widget B  Widgets         5
31     1032 2025-09-30       Mia Anderson  Gadget C  Gadgets         3
32     1033 2025-10-01       Ethan Thomas  Widget C  Widgets         4
33     1034 2025-10-03      Harper Taylor  Gadget A  Gadgets         2
35     1036 2025-10-06  Charlotte Jackson  Gadget B  Gadgets         1
36     1037 2025-10-08       Elijah White  Widget A  Widgets         3
37     1038 2025-10-09      Amelia Harris  Gadget C  Gadgets         5
38     1039 2025-10-11       James Martin  Widget C  Widgets         2
39     1040 2025-10-12    Evelyn Thompson  Gadget A  Gadgets         3

    PricePerUnit  TotalPrice Region
0           20.0        60.0  North
1           35.0        70.0  South
3           50.0       250.0   West
4           25.0       100.0  North
6           30.0        60.0   East
7           35.0       210.0   West
8           20.0        60.0  North
9           50.0       100.0  South
10          25.0       200.0   East
11          40.0        40.0   West
12          30.0        60.0  North
13          35.0       105.0  South
14          20.0        40.0   East
16          20.0       100.0  North
17          35.0       140.0  South
18          25.0       175.0   East
19          40.0       120.0   West
20          30.0        60.0  North
21          35.0       210.0  South
22          20.0        60.0  North
24          25.0       100.0   East
25          50.0       250.0   West
26          30.0        60.0  North
27          40.0       120.0  South
28          20.0        20.0   East
29          35.0       210.0   West
30          25.0       125.0  North
31          50.0       150.0  South
32          30.0       120.0   East
33          40.0        80.0   West
35          35.0        35.0  South
36          20.0        60.0   East
37          50.0       250.0   West
38          30.0        60.0  North
39          40.0       120.0  South  >

**Convert TotalPrice to `float` if necessary**

`sales['TotalPrice'] = sales['TotalPrice'].astype(float)`

-Converts the `TotalPrice` column to a float numbers (decimal numbers)

`print(sales['TotalPrice'].dtype)`

-Prints the data type of the `TotalPrice` Column

In [61]:
sales['TotalPrice'] = sales['TotalPrice'].astype(float)
print(sales['TotalPrice'].dtype)

float64

In [69]:
sales['TotalPrice'] = sales['TotalPrice'].astype(float)
print(sales['TotalPrice'].dtype)
print(sales['TotalPrice'])

float64
0      60.0
1      70.0
3     250.0
4     100.0
6      60.0
7     210.0
8      60.0
9     100.0
10    200.0
11     40.0
12     60.0
13    105.0
14     40.0
16    100.0
17    140.0
18    175.0
19    120.0
20     60.0
21    210.0
22     60.0
24    100.0
25    250.0
26     60.0
27    120.0
28     20.0
29    210.0
30    125.0
31    150.0
32    120.0
33     80.0
35     35.0
36     60.0
37    250.0
38     60.0
39    120.0
Name: TotalPrice, dtype: float64

## **Filtering & Sorting**

Filter orders where Category is  "Gadgets" and TotalPrice >150

In [18]:
import pandas as pd
sales = pd.read_csv('sales_data_200.csv')
sales.dropna (inplace= True)
sales.columns = sales.columns.str.strip()
filtered_orders = sales[(sales['Category'] == 'Gadgets') & (sales['TotalPrice'] > 150)]
filtered_orders

,OrderID,Date,CustomerName,Product,Category,Quantity,UnitPrice,TotalPrice,Region
3,1004,20/08/2025,Noah Jones,Gadget C,Gadgets,5.0,50.0,250.0,West
7,1008,26/08/2025,Sophia Rodriguez,Gadget B,Gadgets,6.0,35.0,210.0,West
21,1022,15/09/2025,Alexander Lee,Gadget B,Gadgets,6.0,35.0,210.0,South
25,1026,21/09/2025,Noah Jones,Gadget C,Gadgets,5.0,50.0,250.0,West
29,1030,27/09/2025,Sophia Rodriguez,Gadget B,Gadgets,6.0,35.0,210.0,West
37,1038,09/10/2025,Amelia Harris,Gadget C,Gadgets,5.0,50.0,250.0,West

**Sort the data by TotalPrice in descending order**

In [19]:
sales_sorted = sales.sort_values (by= 'TotalPrice', ascending= False)
sales_sorted

,OrderID,Date,CustomerName,Product,Category,Quantity,UnitPrice,TotalPrice,Region
3,1004,20/08/2025,Noah Jones,Gadget C,Gadgets,5.0,50.0,250.0,West
25,1026,21/09/2025,Noah Jones,Gadget C,Gadgets,5.0,50.0,250.0,West
37,1038,09/10/2025,Amelia Harris,Gadget C,Gadgets,5.0,50.0,250.0,West
29,1030,27/09/2025,Sophia Rodriguez,Gadget B,Gadgets,6.0,35.0,210.0,West
21,1022,15/09/2025,Alexander Lee,Gadget B,Gadgets,6.0,35.0,210.0,South
7,1008,26/08/2025,Sophia Rodriguez,Gadget B,Gadgets,6.0,35.0,210.0,West
10,1011,30/08/2025,Ethan Thomas,Widget B,Widgets,8.0,25.0,200.0,East
18,1019,11/09/2025,Benjamin Garcia,Widget B,Widgets,7.0,25.0,175.0,East
31,1032,30/09/2025,Mia Anderson,Gadget C,Gadgets,3.0,50.0,150.0,South
17,1018,09/09/2025,Evelyn Thompson,Gadget B,Gadgets,4.0,35.0,140.0,South
30,1031,28/09/2025,Mason Wilson,Widget B,Widgets,5.0,25.0,125.0,North
27,1028,24/09/2025,Isabella Martinez,Gadget A,Gadgets,3.0,40.0,120.0,South
19,1020,12/09/2025,Abigail Martinez,Gadget A,Gadgets,3.0,40.0,120.0,West
39,1040,12/10/2025,Evelyn Thompson,Gadget A,Gadgets,3.0,40.0,120.0,South
32,1033,01/10/2025,Ethan Thomas,Widget C,Widgets,4.0,30.0,120.0,East
13,1014,03/09/2025,Charlotte Jackson,Gadget B,Gadgets,3.0,35.0,105.0,South
4,1005,22/08/2025,Ava Garcia,Widget B,Widgets,4.0,25.0,100.0,North
24,1025,19/09/2025,Olivia Brown,Widget B,Widgets,4.0,25.0,100.0,East
9,1010,29/08/2025,Mia Anderson,Gadget C,Gadgets,2.0,50.0,100.0,South
16,1017,08/09/2025,James Martin,Widget A,Widgets,5.0,20.0,100.0,North
33,1034,03/10/2025,Harper Taylor,Gadget A,Gadgets,2.0,40.0,80.0,West
1,1002,17/08/2025,Liam Smith,Gadget B,Gadgets,2.0,35.0,70.0,South
0,1001,15/08/2025,Emma Johnson,Widget A,Widgets,3.0,20.0,60.0,North
8,1009,28/08/2025,Mason Wilson,Widget A,Widgets,3.0,20.0,60.0,North
6,1007,25/08/2025,Lucas Davis,Widget C,Widgets,2.0,30.0,60.0,East
12,1013,02/09/2025,Logan Moore,Widget C,Widgets,2.0,30.0,60.0,North
20,1021,14/09/2025,Eliana Rodriguez,Widget C,Widgets,2.0,30.0,60.0,North
38,1039,11/10/2025,James Martin,Widget C,Widgets,2.0,30.0,60.0,North
36,1037,08/10/2025,Elijah White,Widget A,Widgets,3.0,20.0,60.0,East
22,1023,16/09/2025,Emma Johnson,Widget A,Widgets,3.0,20.0,60.0,North
26,1027,22/09/2025,Ava Garcia,Widget C,Widgets,2.0,30.0,60.0,North
14,1015,05/09/2025,Elijah White,Widget A,Widgets,2.0,20.0,40.0,East
11,1012,01/09/2025,Harper Taylor,Gadget A,Gadgets,1.0,40.0,40.0,West
35,1036,06/10/2025,Charlotte Jackson,Gadget B,Gadgets,1.0,35.0,35.0,South
28,1029,25/09/2025,Lucas Davis,Widget A,Widgets,1.0,20.0,20.0,East

**Find the top 10 orders by TotalPrice**

In [20]:
# If you just wanted to see the boolean mask for the top 10 orders
sales_sorted.head(10)['TotalPrice'] >=150

3      True
25     True
37     True
29     True
21     True
7      True
10     True
18     True
31     True
17    False
Name: TotalPrice, dtype: bool

In [22]:
# To get the top 10 orders and then filter those where TotalPrice >= 150
top_10_orders = sales_sorted.head(10)
filtered_top_10_orders = top_10_orders[top_10_orders['TotalPrice'] >= 150]
print(filtered_top_10_orders)

    OrderID        Date      CustomerName   Product Category  Quantity  \
3      1004  20/08/2025        Noah Jones  Gadget C  Gadgets       5.0
25     1026  21/09/2025        Noah Jones  Gadget C  Gadgets       5.0
37     1038  09/10/2025     Amelia Harris  Gadget C  Gadgets       5.0
29     1030  27/09/2025  Sophia Rodriguez  Gadget B  Gadgets       6.0
21     1022  15/09/2025     Alexander Lee  Gadget B  Gadgets       6.0
7      1008  26/08/2025  Sophia Rodriguez  Gadget B  Gadgets       6.0
10     1011  30/08/2025      Ethan Thomas  Widget B  Widgets       8.0
18     1019  11/09/2025   Benjamin Garcia  Widget B  Widgets       7.0
31     1032  30/09/2025      Mia Anderson  Gadget C  Gadgets       3.0

    UnitPrice  TotalPrice Region
3        50.0       250.0   West
25       50.0       250.0   West
37       50.0       250.0   West
29       35.0       210.0   West
21       35.0       210.0  South
7        35.0       210.0   West
10       25.0       200.0   East
18       25.0       175.0   East
31       50.0       150.0  South

In [24]:
# Find the last 5 orders in terms of Date
# Sorts the dataset by the date Column
# `ascending=True` means oldest to the newest
# Saves the sorted data in a new table `date_asc`

date_asc = sales.sort_values(by='Date', ascending=True)
date_asc.tail(5)

,OrderID,Date,CustomerName,Product,Category,Quantity,UnitPrice,TotalPrice,Region
8,1009,28/08/2025,Mason Wilson,Widget A,Widgets,3.0,20.0,60.0,North
30,1031,28/09/2025,Mason Wilson,Widget B,Widgets,5.0,25.0,125.0,North
9,1010,29/08/2025,Mia Anderson,Gadget C,Gadgets,2.0,50.0,100.0,South
10,1011,30/08/2025,Ethan Thomas,Widget B,Widgets,8.0,25.0,200.0,East
31,1032,30/09/2025,Mia Anderson,Gadget C,Gadgets,3.0,50.0,150.0,South

## **Task 8: Aggregation & Analysis**

`sales.groupby('Region)` - means  groups data based on the Region column

In [25]:
1. # Count total sales per Region

total_price_per_region = sales.groupby('Region')['TotalPrice'].sum()
print(total_price_per_region)

Region
East      775.0
North     745.0
South    1050.0
West     1410.0
Name: TotalPrice, dtype: float64

In [27]:
2. # Find the average TotalPrice per product

total_price_by_product = sales.groupby ('Product')['TotalPrice'].sum()
print(total_price_by_product)

Product
Gadget A     480.0
Gadget B     980.0
Gadget C    1000.0
Widget A     400.0
Widget B     700.0
Widget C     420.0
Name: TotalPrice, dtype: float64

In [28]:
3. # Alternatively you can also use mean
# Notice the total is in decimal places
# Average is often not a whole number thats why it shows decimals
total_price_by_product = sales.groupby ('Product')['TotalPrice'].mean()
print(total_price_by_product)

Product
Gadget A     96.000000
Gadget B    140.000000
Gadget C    200.000000
Widget A     57.142857
Widget B    140.000000
Widget C     70.000000
Name: TotalPrice, dtype: float64

In [29]:
# To remove the decimal places

total_price_by_product = sales.groupby ('Product')['TotalPrice'].mean()
print(total_price_by_product.astype (int))

Product
Gadget A     96
Gadget B    140
Gadget C    200
Widget A     57
Widget B    140
Widget C     70
Name: TotalPrice, dtype: int64

In [31]:
4. # Count total number of Orders each Customer has placed

customer_order_count = sales.groupby('CustomerName')['OrderID'].count()
print(customer_order_count)

CustomerName
Abigail Martinez     1
Alexander Lee        1
Amelia Harris        1
Ava Garcia           2
Benjamin Garcia      1
Charlotte Jackson    2
Eliana Rodriguez     1
Elijah White         2
Emma Johnson         2
Ethan Thomas         2
Evelyn Thompson      2
Harper Taylor        2
Isabella Martinez    1
James Martin         2
Liam Smith           1
Logan Moore          1
Lucas Davis          2
Mason Wilson         2
Mia Anderson         2
Noah Jones           2
Olivia Brown         1
Sophia Rodriguez     2
Name: OrderID, dtype: int64

### Well done you have learned how to clean data !! Keep Learning